# Generated by Django 5.0.2 on 2024-02-17 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_personas.persona')),
            ],
        ),
    ]
